import type { FormEvent } from 'react'
import type { Booking, CancellationPreview, Journey, JourneyPass, Passenger } from '../types'
import { Icon } from './Icon'

const time = (value: string) => new Intl.DateTimeFormat('en-IN', { hour: 'numeric', minute: '2-digit' }).format(new Date(value))
type BookingProps = { booking: Booking; journey: Journey | null; passengerName: string; passengerAge: string; concessionType: Passenger['concession_type']; failureDemo: boolean; isWorking: boolean; journeyPass: JourneyPass | null; cancellation: CancellationPreview | null; onSeat: (number: string) => void; onPassenger: (event: FormEvent<HTMLFormElement>) => void; onName: (value: string) => void; onAge: (value: string) => void; onConcession: (value: Passenger['concession_type']) => void; onFailureDemo: (value: boolean) => void; onPayment: () => void; onConfirm: () => void; onTicket: () => void; onManage: () => void; onCancel: () => void; onRefund: () => void }

export function BookingFlow(props: BookingProps) {
  const { booking } = props
  return <section className="booking-area" aria-live="polite"><BookingStepper booking={booking} /><div className="booking-layout"><div className="booking-main"><SeatMap booking={booking} onSeat={props.onSeat} />{booking.status === 'SEATS_HELD' && !booking.passenger && <PassengerStep {...props} />}{booking.status === 'SEATS_HELD' && booking.passenger && <PaymentStep {...props} />}{booking.status === 'PAYMENT_RECEIVED' && <section className="transaction-card processing"><p className="kicker">Payment received</p><h2>We’re confirming your seats.</h2><p>Please don’t pay again. Your mock payment reference is {booking.payment_reference}.</p><button className="primary-action" type="button" onClick={props.onConfirm} disabled={props.isWorking}>Confirm reservation <Icon name="arrow" /></button></section>}{booking.status === 'CONFIRMED' && <section className="transaction-card success"><Icon name="check" /><div><p className="kicker">Journey booked</p><h2>Your journey is confirmed.</h2><p>Booking ID: {booking.id}</p></div><div className="action-row"><button className="primary-action" type="button" onClick={props.onTicket} disabled={props.isWorking}><Icon name="ticket" /> View journey pass</button><button className="secondary-action" type="button" onClick={props.onManage} disabled={props.isWorking}>Manage journey</button></div></section>}{booking.status === 'FAILED' && <section className="transaction-card recovery"><p className="kicker">Your payment is safe</p><h2>We couldn’t confirm the reservation.</h2><p>A mock refund is now {booking.refund_status.toLowerCase()}. Your selected seat was released.</p></section>}{booking.status === 'CANCELLED' && <section className="transaction-card recovery"><p className="kicker">Journey cancelled</p><h2>Refund {booking.refund_status.toLowerCase()}.</h2><p>This is a mock refund lifecycle; no bank transfer is made.</p>{booking.refund_status !== 'COMPLETED' && <button className="secondary-action" type="button" onClick={props.onRefund} disabled={props.isWorking}>Advance mock refund</button>}</section>}{props.journeyPass && <JourneyPassCard journeyPass={props.journeyPass} onManage={props.onManage} />}{props.cancellation && <CancellationCard cancellation={props.cancellation} onCancel={props.onCancel} isWorking={props.isWorking} />}</div><JourneySummary journey={props.journey} booking={booking} /></div></section>
}

function BookingStepper({ booking }: { booking: Booking }) {
  const step = booking.status === 'DRAFT' ? 1 : booking.status === 'SEATS_HELD' ? (booking.passenger ? 3 : 2) : booking.status === 'PAYMENT_RECEIVED' ? 4 : 5
  return <ol className="booking-stepper" aria-label="Booking progress">{['Journey', 'Seats', 'Passenger', 'Payment', 'Pass'].map((label, index) => <li key={label} className={step > index + 1 ? 'done' : step === index + 1 ? 'active' : ''}><span>{step > index + 1 ? '✓' : index + 1}</span>{label}</li>)}</ol>
}

function JourneySummary({ journey, booking }: { journey: Journey | null; booking: Booking }) {
  return <aside className="journey-summary-card"><p className="kicker">Your journey</p>{journey ? <><h2>{journey.origin.name} <Icon name="arrow" /> {journey.destination.name}</h2><p>{time(journey.departure_at)} → {time(journey.arrival_at)} · {journey.service_name}</p><p><Icon name="seat" /> {booking.seats.find((seat) => seat.held_by_current_booking)?.number ?? (booking.status === 'CONFIRMED' ? 'Seat confirmed' : 'Choose a seat')}</p></> : <><h2>Existing booking</h2><p>Booking ID: {booking.id}</p></>}<div><span>Fare</span><strong>₹{booking.total_fare_inr || booking.base_fare_inr}</strong></div></aside>
}

function SeatMap({ booking, onSeat }: Pick<BookingProps, 'booking' | 'onSeat'>) {
  return <section className="seat-card"><header><div><p className="kicker">Choose your seat</p><h2>Pick a comfortable place</h2><p>Seats show their availability in text and colour.</p></div><span className="bus-front"><Icon name="bus" /> Front</span></header><div className="seat-legend" aria-label="Seat status legend"><span><i className="available" /> Available</span><span><i className="held" /> Held</span><span><i className="booked" /> Booked</span></div><div className="bus-layout" aria-label="Bus seat map"><span className="driver">Driver</span><div className="seat-grid">{booking.seats.map((seat) => <button key={seat.id} type="button" className={`seat seat-${seat.status.toLowerCase()}`} disabled={seat.status !== 'AVAILABLE' || booking.status === 'SEATS_HELD'} onClick={() => onSeat(seat.number)} aria-label={`Seat ${seat.number}: ${seat.held_by_current_booking ? 'held for you' : seat.status.toLowerCase()}, ${seat.seat_type.toLowerCase()}`}><strong>{seat.number}</strong><span>{seat.held_by_current_booking ? 'Held for you' : seat.status === 'AVAILABLE' ? seat.seat_type === 'WINDOW' ? 'Window' : 'Aisle' : seat.status === 'BOOKED' ? 'Booked' : 'Held'}</span></button>)}</div><span className="aisle" aria-hidden="true">Aisle</span></div>{booking.status === 'SEATS_HELD' && <p className="hold-message"><Icon name="check" /> Your seat is held for 10 minutes while you complete this booking.</p>}</section>
}

function PassengerStep(props: BookingProps) {
  return <section className="form-card"><p className="kicker">Passenger details</p><h2>Who is travelling?</h2><form className="passenger-form" onSubmit={props.onPassenger}><label>Full name<input value={props.passengerName} onChange={(event) => props.onName(event.target.value)} required /></label><label>Age<input type="number" min="1" max="120" value={props.passengerAge} onChange={(event) => props.onAge(event.target.value)} required /></label><fieldset><legend>Concession</legend><label><input type="radio" checked={props.concessionType === 'NONE'} onChange={() => props.onConcession('NONE')} /> No concession</label><label><input type="radio" checked={props.concessionType === 'STUDENT'} onChange={() => props.onConcession('STUDENT')} /> Student</label><label><input type="radio" checked={props.concessionType === 'SENIOR'} onChange={() => props.onConcession('SENIOR')} /> Senior citizen</label></fieldset><p className="support-note">Demo rule: students aged 25 or under receive 10%; seniors aged 60+ receive 20%. This is simulated eligibility, not MSRTC verification.</p><button className="primary-action" disabled={props.isWorking}>Continue to payment <Icon name="arrow" /></button></form></section>
}

function PaymentStep(props: BookingProps) {
  const { booking } = props
  return <section className="form-card"><p className="kicker">Mock payment</p><h2>Review and pay</h2><div className="fare-list"><span>Standard fare</span><strong>₹{booking.base_fare_inr}</strong><span>Concession</span><strong>−₹{booking.concession_discount_inr}</strong><span className="total">Your fare</span><strong className="total">₹{booking.total_fare_inr}</strong></div><label className="demo-toggle"><input type="checkbox" checked={props.failureDemo} onChange={(event) => props.onFailureDemo(event.target.checked)} /> Demonstrate the payment recovery scenario</label><p className="support-note">This is a simulated payment. Selecting the recovery scenario demonstrates payment success followed by reservation-confirmation failure and refund initiation.</p><button className="primary-action" type="button" onClick={props.onPayment} disabled={props.isWorking}>Pay ₹{booking.total_fare_inr} (mock) <Icon name="arrow" /></button></section>
}

function JourneyPassCard({ journeyPass, onManage }: { journeyPass: JourneyPass; onManage: () => void }) {
  return <section className="journey-pass-card"><header><span><Icon name="check" /> Journey confirmed</span><span className="pass-ticket">Ticket {journeyPass.ticket_number}</span></header><h2>{journeyPass.boarding_point} <Icon name="arrow" /> {journeyPass.destination}</h2><p>{time(journeyPass.departure_at)} → {time(journeyPass.arrival_at)} · {journeyPass.service_name}</p><div className="pass-grid"><span>Boarding<strong>{journeyPass.boarding_point}</strong></span><span>Seat<strong>{journeyPass.seat_numbers.join(', ')}</strong></span><span>Passenger<strong>{journeyPass.passenger_name}</strong></span><span>Paid<strong>₹{journeyPass.paid_amount_inr}</strong></span></div><code>{journeyPass.qr_payload}</code><p className="pass-note">QR identifier is simulated for this prototype.</p><button className="pass-manage" type="button" onClick={onManage}>Manage journey</button></section>
}

function CancellationCard({ cancellation, onCancel, isWorking }: { cancellation: CancellationPreview; onCancel: () => void; isWorking: boolean }) {
  return <section className="form-card cancellation-card"><p className="kicker">Cancellation</p><h2>{cancellation.can_cancel ? 'Cancel this journey?' : 'Cancellation unavailable'}</h2>{cancellation.can_cancel ? <><div className="fare-list"><span>You paid</span><strong>₹{cancellation.paid_amount_inr}</strong><span>Cancellation deduction</span><strong>−₹{cancellation.deduction_inr}</strong><span>Non-refundable charge</span><strong>−₹{cancellation.non_refundable_charges_inr}</strong><span className="total">You’ll receive</span><strong className="total">₹{cancellation.refund_amount_inr}</strong></div><p className="support-note">Cancel before {cancellation.deadline && time(cancellation.deadline)}. This uses the existing mock refund policy.</p><button className="danger-action" type="button" onClick={onCancel} disabled={isWorking}>Cancel journey</button></> : <p>{cancellation.reason}</p>}</section>
}
