import type { FormEvent } from 'react'
import type { ApiError, ConnectingJourney, Journey, StopCandidate } from '../types'
import { Icon } from './Icon'

const dateText = (value: string) => new Intl.DateTimeFormat('en-IN', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(`${value}T12:00:00`))
const time = (value: string) => new Intl.DateTimeFormat('en-IN', { hour: 'numeric', minute: '2-digit' }).format(new Date(value))
const duration = (minutes: number) => `${Math.floor(minutes / 60)}h ${minutes % 60}m`

type SearchProps = { origin: string; destination: string; journeyDate: string; timeStart: string; timeEnd: string; acOnly: boolean; naturalQuery: string; isLoading: boolean; isParsing: boolean; intentMessage: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onNatural: () => void; setOrigin: (value: string) => void; setDestination: (value: string) => void; setJourneyDate: (value: string) => void; setTimeStart: (value: string) => void; setTimeEnd: (value: string) => void; setAcOnly: (value: boolean) => void; setNaturalQuery: (value: string) => void; onQuickRoute: (destination: string) => void }

export function SearchHero(props: SearchProps) {
  return <section className="hero" aria-labelledby="hero-title"><p className="kicker">Maharashtra moves with MSRTC</p><h1 id="hero-title">Where do you want to go?</h1><p className="hero-copy">Plan a bus journey with the places you know. We make the transport details clear.</p><form id="journey-search" className="journey-search" onSubmit={props.onSubmit}><div className="journey-fields"><label><span>From</span><span className="field-control"><Icon name="location" /><input value={props.origin} onChange={(event) => props.setOrigin(event.target.value)} required /></span></label><span className="journey-arrow" aria-hidden="true"><Icon name="arrow" /></span><label><span>To</span><span className="field-control"><Icon name="location" /><input value={props.destination} onChange={(event) => props.setDestination(event.target.value)} required /></span></label><label><span>When</span><span className="field-control"><Icon name="calendar" /><input type="date" value={props.journeyDate} onChange={(event) => props.setJourneyDate(event.target.value)} required /></span></label></div><div className="search-actions"><label className="compact-field"><span>Earliest</span><input type="time" value={props.timeStart} onChange={(event) => props.setTimeStart(event.target.value)} /></label><label className="compact-field"><span>Latest</span><input type="time" value={props.timeEnd} onChange={(event) => props.setTimeEnd(event.target.value)} /></label><label className="filter-check"><input type="checkbox" checked={props.acOnly} onChange={(event) => props.setAcOnly(event.target.checked)} /> AC only</label><button className="primary-action" type="submit" disabled={props.isLoading}>{props.isLoading ? `Finding buses from ${props.origin}…` : <>Find buses <Icon name="arrow" /></>}</button></div></form><div className="natural-search"><div><p className="natural-title"><Icon name="sparkle" /> Tell us your journey</p><p>Try: “Pune to Nashik tomorrow morning, AC”</p></div><label className="natural-input"><span className="sr-only">Describe your journey</span><input value={props.naturalQuery} onChange={(event) => props.setNaturalQuery(event.target.value)} /><button type="button" onClick={props.onNatural} disabled={props.isParsing} aria-label="Use natural-language journey request"><Icon name="arrow" /></button></label>{props.intentMessage && <p className="intent-message" aria-live="polite">{props.intentMessage}</p>}</div><section className="quick-routes" aria-label="Quick route choices"><p>Try a demo journey</p><div><button type="button" onClick={() => props.onQuickRoute('Nashik Mahamarg')}>Pune <Icon name="arrow" /> Nashik</button><button type="button" onClick={() => props.onQuickRoute('Demo Destination')}>Pune <Icon name="arrow" /> Demo Destination</button></div></section></section>
}

export function ErrorState({ error, onChoose }: { error: ApiError; onChoose: (candidate: StopCandidate) => void }) {
  return <section className="state-card state-error" role="alert"><p className="kicker">We need one detail</p><h2>{error.code === 'AMBIGUOUS_STOP' ? 'Choose the right stop' : 'We couldn’t complete that request'}</h2><p>{error.message}</p>{error.details.candidates && <div className="stop-options">{error.details.candidates.map((candidate) => <button key={candidate.id} type="button" onClick={() => onChoose(candidate)}><Icon name="location" /><span><strong>{candidate.name}</strong><small>{candidate.description}</small></span><Icon name="chevron" /></button>)}</div>}</section>
}

export function Results({ results, connections, origin, destination, journeyDate, sortBy, onSort, onSelect }: { results: Journey[]; connections: ConnectingJourney[]; origin: string; destination: string; journeyDate: string; sortBy: string; onSort: (value: string) => void; onSelect: (journey: Journey) => void }) {
  if (!results.length && !connections.length) return null
  const sorts = [['recommended', 'Recommended'], ['fastest', 'Fastest'], ['cheapest', 'Cheapest'], ['earliest', 'Earliest']]
  return <section className="results-section" aria-live="polite"><div className="search-summary"><div><p className="kicker">Your journey</p><h2>{origin} <Icon name="arrow" /> {destination}</h2><p>{dateText(journeyDate)} · 1 passenger</p></div><a href="#journey-search">Change search</a></div>{results.length > 0 && <><div className="results-heading"><div><h2>Buses for your journey</h2><p>Choose the service that works best for you.</p></div><div className="sort-tabs" aria-label="Sort buses">{sorts.map(([value, label]) => <button key={value} type="button" className={sortBy === value ? 'selected' : ''} onClick={() => onSort(value)}>{label}</button>)}</div></div><div className="service-list">{results.map((journey, index) => <ServiceCard key={journey.id} journey={journey} recommended={index === 0 && sortBy === 'recommended'} onSelect={onSelect} />)}</div></>}{connections.map((connection) => <ConnectionCard key={connection.id} connection={connection} />)}</section>
}

function ServiceCard({ journey, recommended, onSelect }: { journey: Journey; recommended: boolean; onSelect: (journey: Journey) => void }) {
  return <article className={`service-card ${recommended ? 'recommended' : ''}`}>{recommended && <span className="recommendation">Recommended</span>}<header><div><p className="service-name">{journey.service_name}</p><p>{journey.is_air_conditioned ? 'Air conditioned' : 'Non-AC'} · {journey.service_type}</p></div><strong className="price">₹{journey.fare_inr}</strong></header><div className="time-route"><div><strong>{time(journey.departure_at)}</strong><span>{journey.origin.name}</span></div><div className="duration"><span>{duration(journey.duration_minutes)}</span><i /></div><div className="arrival"><strong>{time(journey.arrival_at)}</strong><span>{journey.destination.name}</span></div></div><div className="service-details"><span><Icon name="location" /> {journey.origin.name} → {journey.destination.name}</span><span><Icon name="seat" /> {journey.available_seats} of {journey.total_seats} seats available</span></div><button type="button" className="primary-action" onClick={() => onSelect(journey)}>Select this bus <Icon name="arrow" /></button></article>
}

function ConnectionCard({ connection }: { connection: ConnectingJourney }) {
  return <article className="connection-journey"><header><p className="kicker">We can still get you there</p><h2>One simple connection</h2><p>No direct bus is available, but this journey keeps you moving.</p></header><div className="connection-timeline">{connection.segments.map((segment, index) => <div className="timeline-leg" key={segment.trip_id}><div className="timeline-dot" /><div><strong>{time(segment.departure_at)} · {segment.origin.name}</strong><span>{segment.service_name} · {duration(segment.duration_minutes)}</span><small>{time(segment.arrival_at)} · {segment.destination.name}</small></div>{index === 0 && <div className="transfer-note"><Icon name="clock" /><span>Change at {connection.transfer_stop.name} · {duration(connection.transfer_minutes)} transfer</span></div>}</div>)}</div><footer><span>{duration(connection.total_duration_minutes)} total · {connection.available_seats} seats available</span><strong>₹{connection.total_fare_inr}</strong></footer><p className="prototype-limit">This prototype presents the connection; linked multi-leg booking is not yet available.</p></article>
}
