export type Locale = 'en' | 'mr'
export const LOCALE_STORAGE_KEY = 'msrtc-journey-locale'

type Dictionary = Record<string, string>
const en: Dictionary = {
  'login.eyebrow':'Demo access','login.title':'Welcome aboard.','login.intro':'Sign in with the prototype account to explore journey planning and booking.','login.username':'Username','login.password':'Password','login.submit':'Enter prototype','login.credentials':'Demo credentials','login.disclosure':'Frontend-only access for demonstration purposes. This is not secure authentication and does not protect backend data.','login.error':'That username or password does not match the demo account.','login.useCredentials':'Use demo account',
  'nav.plan':'Plan journey','nav.booking':'My bookings','nav.guide':'Round 2 upgrades','nav.report':'Report an issue','nav.signOut':'Sign out','nav.prototype':'Prototype','nav.menu':'Open menu','nav.status':'Service status',
  'search.from':'From','search.to':'To','search.date':'Travel date','search.submit':'Find buses','search.manual':'Or search manually','search.ai':'AI journey planner','search.placeholder':'Describe your journey — e.g. Pune to Nashik tomorrow morning, AC','search.change':'Change search','search.journey':'Your journey','search.passengers':'1 passenger','search.acOnly':'AC only','search.corporation':'Maharashtra State Road Transport Corporation',
  'search.nextAvailable':'The selected date is full, so we’re showing the next available demo journey on {date}.',
  'voice.start':'Speak your journey','voice.listening':'Listening…','voice.cancel':'Stop listening','voice.help':'Speak in Marathi or English. Your words stay editable before we search.',
  'voice.captured':'Voice request captured','voice.review':'Review the words above. AI will understand the places, date, time, and bus preference before searching.','voice.plan':'Plan with AI','voice.processing':'Understanding your journey and matching services','voice.planning':'Planning','voice.planningLabel':'AI is planning your journey','voice.fallback':'I recognised your stops and am finding services.','voice.needsDetails':'I could hear your words, but could not match them to supported stops. Please edit the journey and try again.','voice.parserUnavailable':'The AI interpretation service is unavailable. Please edit the journey and try again.',
  'results.available':'Available services','results.choose':'Choose how you travel.','results.recommended':'Recommended','results.fastest':'Fastest','results.cheapest':'Cheapest','results.earliest':'Earliest','results.airConditioned':'Air conditioned','results.nonAc':'Non-AC','results.seatsLeft':'{count} seats left','results.fare':'Fare','results.select':'Select',
  'booking.back':'Back to services','booking.seat':'Seat','booking.passenger':'Passenger','booking.payment':'Payment','booking.confirm':'Confirm','booking.selectSeat':'Select your seat','booking.place':'Choose your place on board.','booking.hold':'Your selection is held for 10 minutes while you complete your booking.','booking.front':'Front of bus','booking.driver':'Driver','booking.aisle':'Aisle','booking.available':'Available','booking.held':'Held','booking.booked':'Booked','booking.selected':'Selected','booking.connectedItinerary':'Your two-bus journey','booking.busNumber':'Bus {count}','booking.twoBuses':'This booking includes two buses.','booking.connectedSeatNote':'Choose one seat on each bus. We reserve both together only after you have selected both seats.','booking.reserveBoth':'Reserve both seats','booking.details':'Passenger details','booking.who':'Who is travelling?','booking.name':'Full name','booking.age':'Age','booking.concession':'Concession','booking.none':'No concession','booking.student':'Student','booking.senior':'Senior citizen','booking.continue':'Continue to payment','booking.mockPayment':'Mock payment','booking.review':'Review and pay.','booking.manage':'Manage journey','booking.pass':'Journey pass',
  'pass.confirmed':'Journey confirmed','pass.ticket':'Ticket number','pass.boarding':'Boarding','pass.destination':'Destination','pass.seat':'Seat','pass.paid':'Paid','pass.twoBuses':'Two buses · change at {stop}','pass.connected':'Your two-bus itinerary','pass.busNumber':'Bus {count}','pass.changeAt':'Change buses at {stop}. Remain at the same station.','pass.transfer':'Change at',
  'tracking.title':'Track your bus','tracking.mock':'Synthetic tracking — not live MSRTC GPS','tracking.busNumber':'Bus number','tracking.status':'Journey status','tracking.back':'My bookings','tracking.location':'Vehicle location will appear here closer to departure.',
  'tracking.progress':'Journey progress','tracking.currentPosition':'Current position','tracking.lastUpdated':'Last updated','tracking.nextMilestone':'Next stop','tracking.scheduled':'Scheduled departure','tracking.progressValue':'{value}% of this bus route','tracking.enRoute':'En route to {stop}',
  'complaint.title':'Report an issue','complaint.mock':'This simulated complaint is not sent to MSRTC.','complaint.feedback':'Journey-linked feedback','complaint.what':'What happened?','complaint.choose':'Choose the closest issue','complaint.photo':'Photo evidence','complaint.optional':'optional, image up to 5 MB','complaint.addPhoto':'Add a photo from camera or library','complaint.replacePhoto':'Replace selected photo','complaint.remove':'Remove','complaint.submit':'Submit simulated complaint','complaint.journeyDetails':'Journey details',
  'complaint.entryEyebrow':'Passenger support','complaint.entryTitle':'Report an issue','complaint.entryIntro':'Choose the journey involved. We’ll carry its details into your report.','complaint.savedTitle':'Choose an online booking','complaint.useBooking':'Online booking','complaint.manualTitle':'Journey booked offline','complaint.manualIntro':'No online booking or ticket number is required.','complaint.manualAction':'Enter journey details','complaint.offlineSource':'Counter or onboard ticket','complaint.manualOrigin':'From','complaint.manualDestination':'To','complaint.manualDate':'Journey date','complaint.offlineTicket':'Offline ticket number','complaint.ticketOptional':'Optional','complaint.backChoices':'Back to reporting options','complaint.scopeTitle':'What can be reported','complaint.scopeText':'Bus condition, staff, delays, safety, cleanliness and station facilities.',
  'common.back':'Back','common.close':'Close','common.prototype':'Prototype booking · no real payment is made',
  'pass.keep':'Keep this pass ready while boarding. This prototype does not represent a real MSRTC ticket or payment.','pass.back':'Booking','pass.label':'Journey pass · Prototype','pass.qr':'Simulated QR identifier','manage.label':'Booking management · Prototype','manage.existing':'Existing journey','manage.open':'Open a booking.','manage.id':'Booking ID','manage.openAction':'Open journey','manage.title':'Manage journey','manage.cancel':'Cancellation','manage.cancelQuestion':'Cancel this journey?','manage.cancelled':'Journey cancelled','manage.track':'Track your bus','manage.saved':'Saved in this browser','manage.recent':'Your recent bookings','manage.twoBus':'Two-bus journey','manage.direct':'Direct journey','manage.browserOnly':'Shown only in this browser for the prototype.','fare.standard':'Standard fare','fare.concession':'Concession','fare.pay':'You pay','fare.paid':'You paid','fare.deduction':'Cancellation deduction','fare.receive':'You’ll receive','status.confirmed':'Confirmed','status.notSelected':'Not selected',
  'error.confirmDestination':'Confirm your destination','error.whichStop':'Which stop did you mean?','error.chooseStop':'Choose the stop you mean.','error.planner':'Journey planner','error.wrong':'Something went wrong','error.return':'Return to journey planner','error.editJourney':'Edit journey details',
  'prototype.requestReceived':'Request understood','prototype.understood':'That route isn’t available here.','prototype.outside':'You asked for {origin} → {destination}. That journey is outside this intentionally small prototype network.','prototype.requested':'You searched for','prototype.limitation':'It isn’t included in the current prototype data.','prototype.availableJourneys':'Available in this prototype','prototype.puneNashik':'Pune → Nashik','prototype.chooseNashik':'Choose a Nashik stop','prototype.mumbaiPune':'Mumbai → Pune','prototype.direct':'Direct','prototype.puneSatara':'Pune → Satara','prototype.puneDemo':'Pune → Demo Destination','prototype.connection':'One connection via Satara','prototype.choose':'Try a supported journey',
  'a11y.primaryNav':'Primary navigation','a11y.language':'Language','a11y.goPlanner':'Go to journey planner','a11y.journeyPlanner':'Journey planner','a11y.currentSearch':'Current search','a11y.sort':'Sort services','a11y.bookingProgress':'Booking progress','a11y.planning':'Planning journey',
  'search.hero':'Tell us where you want to go. We’ll find the right ST service.','search.finding':'Finding buses…','search.understood':'Journey understood. Finding buses…','search.unavailable':'Natural-language search is unavailable. Use the journey fields instead.','search.demoJourneys':'Demo journeys','search.tryRoute':'Try a supported route','search.demoJourneyCount':'Try one of {count} demo journeys','search.aboutDemo':'About the demo data','search.supported':'Supported demo journeys','search.viewExamples':'View examples','search.demoHubs':'demo hubs','search.demoRoutes':'demo routes','search.syntheticFooter':'Prototype journey service using synthetic schedules','search.noPaymentFooter':'No real booking or payment is made','search.puneNashikHint':'Choose your Nashik stop','search.mumbaiPuneHint':'Shivneri and E-Shivai','search.directService':'Direct service','search.connectionHint':'One connection via Satara',
  'network.eyebrow':'Illustrative synthetic data','network.title':'Supported demo journeys','network.range':'This prototype intentionally supports only the examples below, from {start} through {end}.','network.tomorrow':'tomorrow','network.nextDays':'the next 14 days','network.puneNashik':'Direct. Select Mahamarg, CBS, or Nashik Road.','network.mumbaiPune':'Direct premium and standard examples.','network.puneSatara':'Direct example.','network.puneDemo':'One connection via Satara.','network.disclaimer':'Schedules, fares, tracking, and availability are synthetic—not official MSRTC data.',
  'connection.eyebrow':'Connecting journey','connection.changeOnce':'Change once at {stop}.','connection.total':'{duration} total','connection.transfer':'Change at {stop} · {duration}','connection.summary':'One journey, with a change at {stop}.','connection.help':'Stay at the same bus station. Both buses remain visible during booking and on your Journey Pass.','connection.choose':'Choose this journey',
  'booking.progress':'Booking progress','booking.prototypeOnly':'Prototype only:','booking.fakeDetails':'use a made-up name and do not enter real personal information.','booking.eligibility':'Eligibility is simulated. Students aged 25 or under receive 10%; seniors aged 60+ receive 20%.','booking.recovery':'Demonstrate payment recovery','booking.recoveryHelp':'Simulate a successful payment followed by a reservation failure.','booking.paymentNotice':'This is a simulated payment; no money is transferred.','booking.payMock':'Pay ₹{amount} (mock)','booking.paymentReceived':'Payment received','booking.confirmReservation':'Confirm your reservation.','booking.confirmHelp':'Your mock payment is safe. Please confirm once and do not pay again.','booking.confirmSeats':'Confirm seats','booking.journeyBooked':'Journey booked','booking.ready':'You’re ready to travel.','booking.reference':'Booking {id}','booking.openPass':'Open journey pass','booking.paymentProtected':'Payment protected','booking.notConfirmed':'We couldn’t confirm your seat.','booking.refundPending':'Your mock payment was received and a refund is {status}. The seat is available again.','booking.window':'Window',
  'receipt.glance':'Booking at a glance','receipt.passengerNext':'Passenger details next','receipt.twoTickets':'Two boarding tickets','receipt.status':'Status','receipt.total':'Total fare',
  'manage.yourBooking':'Your booking','manage.bookingId':'Booking ID: {id}','manage.deadline':'Deadline {time}','manage.refund':'Refund {status}','manage.refundHelp':'The cancellation is complete. Refund progress is simulated for this prototype.','manage.advanceRefund':'Advance mock refund','manage.reviewRefund':'Review the refund above before cancelling. This action releases the booked seat.','manage.cancelAction':'Cancel journey','manage.cannotCancel':'This journey can no longer be cancelled.','fare.nonRefundable':'Non-refundable charge',
  'tracking.awaiting':'Awaiting assignment','tracking.departure':'Departure {time}','tracking.updated':'Updated {time}','tracking.nextStop':'Next stop: {stop}','tracking.simulation':'This route position is a synthetic prototype simulation, not a live MSRTC GPS feed.','tracking.demoState':'Prototype state','tracking.changeState':'Preview another tracking state','tracking.notice':'Prototype notification: bus assignment and trip-start updates would appear here in the production experience.','tracking.state.BUS_NOT_ASSIGNED':'Not yet available','tracking.state.BUS_ASSIGNED':'Bus assigned','tracking.state.TRACKING_AVAILABLE':'Tracking available','tracking.state.TRIP_STARTED':'Trip started','tracking.state.LOCATION_STALE':'Location stale','tracking.state.TRIP_COMPLETED':'Trip completed','tracking.message.BUS_NOT_ASSIGNED':'Bus details will appear once the vehicle is assigned.','tracking.message.BUS_ASSIGNED':'Your bus has been assigned.','tracking.message.TRACKING_AVAILABLE':'Tracking will become available closer to departure.','tracking.message.TRIP_STARTED':'Live location from the synthetic prototype feed.','tracking.message.LOCATION_STALE':'Location has not updated recently.','tracking.message.TRIP_COMPLETED':'This journey has been completed.',
  'complaint.prefilled':'{journey}. We filled in the journey details already.','complaint.booking':'Booking {id}. We filled in the journey details already.','complaint.selected':'Selected: {name}','complaint.tooLarge':'Choose an image smaller than 5 MB.','complaint.invalidType':'Choose an image file such as JPG, PNG, or HEIC.','complaint.photoPreview':'Selected evidence preview','complaint.submitted':'Simulated complaint submitted','complaint.thanks':'Thank you for reporting this.','complaint.reference':'Reference','complaint.journey':'Journey','complaint.category':'Category','complaint.status':'Status','complaint.evidence':'Attached evidence','complaint.passenger':'Passenger','complaint.date':'Travel date','complaint.service':'Service','complaint.boarding':'Boarding point','complaint.destination':'Destination','complaint.seats':'Seats','complaint.bus':'Assigned bus',
  'complaint.category.BUS CONDITION':'Bus condition','complaint.category.STAFF':'Staff','complaint.category.JOURNEY':'Journey','complaint.category.SAFETY':'Safety','complaint.category.CLEANLINESS':'Cleanliness','complaint.category.FACILITIES':'Facilities','complaint.category.OTHER':'Other','complaint.issue.Broken seat':'Broken seat','complaint.issue.AC not working':'AC not working','complaint.issue.Window issue':'Window issue','complaint.issue.Charging point not working':'Charging point not working','complaint.issue.Cleanliness issue':'Cleanliness issue','complaint.issue.Other bus-condition issue':'Other bus-condition issue','complaint.issue.Conductor behaviour':'Conductor behaviour','complaint.issue.Driver behaviour':'Driver behaviour','complaint.issue.Ticketing issue':'Ticketing issue','complaint.issue.Other staff issue':'Other staff issue','complaint.issue.Bus delayed':'Bus delayed','complaint.issue.Bus did not arrive':'Bus did not arrive','complaint.issue.Wrong boarding information':'Wrong boarding information','complaint.issue.Unscheduled stop':'Unscheduled stop','complaint.issue.Other journey issue':'Other journey issue','complaint.issue.Unsafe driving':'Unsafe driving','complaint.issue.Safety concern':'Safety concern','complaint.issue.Bus cleanliness':'Bus cleanliness','complaint.issue.Waiting-area issue':'Waiting-area issue','complaint.issue.Other issue':'Other issue',
  'voice.permission':'Requesting microphone access…','voice.unsupported':'Voice search is not available in this browser. You can still type your journey.','voice.denied':'Microphone permission was denied. You can still type your journey.','voice.transcribing':'Transcribing your journey…','voice.recordingError':'Voice recording could not finish. You can still type your journey.','voice.noSpeech':'We did not hear a journey request. Please try again or type it instead.','voice.transcriptionError':'Voice transcription could not finish. You can still type your journey.','voice.stopped':'Voice search stopped. Your typed journey is unchanged.',
  'api.SERVICE_UNAVAILABLE':'The service is temporarily unavailable. Your details are still here—please try again.','api.PHOTO_TOO_LARGE':'Choose an image smaller than 5 MB.','api.PHOTO_INVALID_TYPE':'Choose an image file such as JPG, PNG, or HEIC.','api.BOOKING_NOT_FOUND':'We could not find that booking. Check the booking ID and try again.','api.DATE_OUT_OF_RANGE':'Choose a date between {start} and {end} for this prototype.','api.DATE_OUTSIDE_DEMO_WINDOW':'Choose a date between {start} and {end} for this prototype.','api.INVALID_CONNECTION':'Those services no longer form a valid connection. Please search again.','api.TRIP_UNAVAILABLE':'One of those buses no longer has a seat available. Please search again.','api.INVALID_SEAT_SELECTION':'Choose one seat on each bus.','api.default':'We could not complete that action. Please try again.',
  'status.DRAFT':'Draft','status.SEATS_HELD':'Seats held','status.PAYMENT_PENDING':'Payment pending','status.PAYMENT_RECEIVED':'Payment received','status.CONFIRMING':'Confirming','status.CONFIRMED':'Confirmed','status.CANCELLED':'Cancelled','status.FAILED':'Failed','status.PENDING':'pending','status.PROCESSING':'processing','status.COMPLETED':'completed','status.SUBMITTED':'Submitted','status.UNDER_REVIEW':'Under review','status.RESOLVED':'Resolved',
}
const mr: Dictionary = {
  'login.eyebrow':'नमुना प्रवेश','login.title':'प्रवासासाठी स्वागत आहे.','login.intro':'प्रवास नियोजन आणि बुकिंग पाहण्यासाठी नमुना खात्याने प्रवेश करा.','login.username':'वापरकर्तानाव','login.password':'पासवर्ड','login.submit':'नमुना उघडा','login.credentials':'नमुना प्रवेश माहिती','login.disclosure':'हा प्रवेश फक्त नमुना दाखवण्यासाठी आहे. हे सुरक्षित प्रमाणीकरण नाही आणि बॅकएंड माहितीचे संरक्षण करत नाही.','login.error':'वापरकर्तानाव किंवा पासवर्ड नमुना खात्याशी जुळत नाही.','login.useCredentials':'नमुना खाते वापरा',
  'nav.plan':'प्रवास नियोजन','nav.booking':'माझे बुकिंग','nav.guide':'राऊंड २ सुधारणा','nav.report':'समस्या नोंदवा','nav.signOut':'बाहेर पडा','nav.prototype':'नमुना','nav.menu':'मेनू उघडा','nav.status':'सेवेची स्थिती',
  'search.from':'कुठून','search.to':'कुठे','search.date':'प्रवासाची तारीख','search.submit':'बस शोधा','search.manual':'किंवा तपशील भरून शोधा','search.ai':'एआय प्रवास नियोजक','search.placeholder':'प्रवास सांगा — उदा. पुणे ते नाशिक उद्या सकाळी, एसी','search.change':'शोध बदला','search.journey':'तुमचा प्रवास','search.passengers':'1 प्रवासी','search.acOnly':'फक्त एसी','search.corporation':'महाराष्ट्र राज्य मार्ग परिवहन महामंडळ',
  'search.nextAvailable':'निवडलेल्या तारखेची आसने भरली आहेत, म्हणून {date} चा पुढील उपलब्ध नमुना प्रवास दाखवत आहोत.',
  'voice.start':'तुमचा प्रवास बोला','voice.listening':'ऐकत आहोत…','voice.cancel':'ऐकणे थांबवा','voice.help':'मराठी किंवा इंग्रजीत बोला. शोधण्यापूर्वी तुमचे शब्द बदलता येतील.',
  'voice.captured':'आवाजातील विनंती नोंदवली','voice.review':'वरील शब्द तपासा. शोधण्यापूर्वी एआय ठिकाण, तारीख, वेळ आणि बसची पसंती समजून घेईल.','voice.plan':'एआयकडून प्रवास नियोजित करा','voice.processing':'तुमचा प्रवास समजून योग्य सेवा शोधत आहोत','voice.planning':'नियोजन सुरू आहे','voice.planningLabel':'एआय तुमच्या प्रवासाचे नियोजन करत आहे','voice.fallback':'तुमची बसस्थानके ओळखली आहेत; सेवा शोधत आहोत.','voice.needsDetails':'तुमचे शब्द ऐकू आले, पण त्यांचा समर्थित बसस्थानकांशी मेळ बसला नाही. प्रवास बदला आणि पुन्हा प्रयत्न करा.','voice.parserUnavailable':'एआय अर्थ समजून घेण्याची सेवा उपलब्ध नाही. प्रवास बदला आणि पुन्हा प्रयत्न करा.',
  'results.available':'उपलब्ध सेवा','results.choose':'तुमचा प्रवास निवडा.','results.recommended':'शिफारस केलेले','results.fastest':'सर्वात जलद','results.cheapest':'सर्वात स्वस्त','results.earliest':'सर्वात लवकर','results.airConditioned':'वातानुकूलित','results.nonAc':'विनाएसी','results.seatsLeft':'{count} जागा शिल्लक','results.fare':'भाडे','results.select':'निवडा',
  'booking.back':'सेवांकडे परत','booking.seat':'आसन','booking.passenger':'प्रवासी','booking.payment':'पेमेंट','booking.confirm':'पुष्टी','booking.selectSeat':'आसन निवडा','booking.place':'बसतील तुमची जागा निवडा.','booking.hold':'बुकिंग पूर्ण होईपर्यंत तुमची निवड 10 मिनिटांसाठी राखीव राहील.','booking.front':'बसचा पुढील भाग','booking.driver':'चालक','booking.aisle':'मार्गिका','booking.available':'उपलब्ध','booking.held':'राखीव','booking.booked':'बुक केलेले','booking.selected':'निवडलेले','booking.connectedItinerary':'तुमचा दोन बसांचा प्रवास','booking.busNumber':'बस {count}','booking.twoBuses':'या बुकिंगमध्ये दोन बस आहेत.','booking.connectedSeatNote':'प्रत्येक बसमध्ये एक आसन निवडा. दोन्ही आसने निवडल्यानंतरच ती एकत्र राखीव केली जातील.','booking.reserveBoth':'दोन्ही आसने राखीव करा','booking.details':'प्रवाशाची माहिती','booking.who':'प्रवास कोण करणार आहे?','booking.name':'पूर्ण नाव','booking.age':'वय','booking.concession':'सवलत','booking.none':'सवलत नाही','booking.student':'विद्यार्थी','booking.senior':'ज्येष्ठ नागरिक','booking.continue':'पेमेंटकडे जा','booking.mockPayment':'नमुना पेमेंट','booking.review':'तपासा आणि पेमेंट करा.','booking.manage':'प्रवास व्यवस्थापित करा','booking.pass':'प्रवास पास',
  'pass.confirmed':'प्रवास निश्चित झाला','pass.ticket':'तिकीट क्रमांक','pass.boarding':'चढण्याचे ठिकाण','pass.destination':'गंतव्य','pass.seat':'आसन','pass.paid':'भरलेले','pass.twoBuses':'दोन बस · {stop} येथे बस बदला','pass.connected':'तुमचा दोन बसांचा प्रवास','pass.busNumber':'बस {count}','pass.changeAt':'{stop} येथे बस बदला. त्याच स्थानकावर थांबा.','pass.transfer':'बदलाचे ठिकाण',
  'tracking.title':'तुमची बस शोधा','tracking.mock':'कृत्रिम ट्रॅकिंग — प्रत्यक्ष MSRTC GPS नाही','tracking.busNumber':'बस क्रमांक','tracking.status':'प्रवासाची स्थिती','tracking.back':'माझे बुकिंग','tracking.location':'प्रस्थानाच्या जवळ वाहनाचे स्थान येथे दिसेल.',
  'tracking.progress':'प्रवासाची प्रगती','tracking.currentPosition':'सध्याचे स्थान','tracking.lastUpdated':'शेवटचे अद्यतन','tracking.nextMilestone':'पुढील थांबा','tracking.scheduled':'नियोजित प्रस्थान','tracking.progressValue':'या बस मार्गाचा {value}% प्रवास','tracking.enRoute':'{stop} कडे प्रवास सुरू',
  'complaint.title':'समस्या नोंदवा','complaint.mock':'ही तक्रार केवळ नमुना आहे; ती MSRTC ला पाठवली जाणार नाही.','complaint.feedback':'प्रवासाशी जोडलेला अभिप्राय','complaint.what':'काय झाले?','complaint.choose':'योग्य समस्या निवडा','complaint.photo':'फोटो पुरावा','complaint.optional':'ऐच्छिक, 5 MB पर्यंत प्रतिमा','complaint.addPhoto':'कॅमेरा किंवा फोटो संग्रहातून फोटो जोडा','complaint.replacePhoto':'निवडलेला फोटो बदला','complaint.remove':'काढून टाका','complaint.submit':'नमुना तक्रार पाठवा','complaint.journeyDetails':'प्रवासाचा तपशील',
  'complaint.entryEyebrow':'प्रवासी सहाय्य','complaint.entryTitle':'समस्या नोंदवा','complaint.entryIntro':'संबंधित प्रवास निवडा. त्याची माहिती तुमच्या तक्रारीत आपोआप भरली जाईल.','complaint.savedTitle':'ऑनलाइन बुकिंग निवडा','complaint.useBooking':'ऑनलाइन बुकिंग','complaint.manualTitle':'ऑफलाइन बुक केलेला प्रवास','complaint.manualIntro':'ऑनलाइन बुकिंग किंवा तिकीट क्रमांक आवश्यक नाही.','complaint.manualAction':'प्रवासाची माहिती भरा','complaint.offlineSource':'काउंटर किंवा बसमधील तिकीट','complaint.manualOrigin':'कुठून','complaint.manualDestination':'कुठे','complaint.manualDate':'प्रवासाची तारीख','complaint.offlineTicket':'ऑफलाइन तिकीट क्रमांक','complaint.ticketOptional':'ऐच्छिक','complaint.backChoices':'तक्रार पर्यायांकडे परत','complaint.scopeTitle':'कशाबद्दल तक्रार करता येईल','complaint.scopeText':'बसची स्थिती, कर्मचारी, विलंब, सुरक्षितता, स्वच्छता आणि स्थानक सुविधा.',
  'common.back':'मागे','common.close':'बंद करा','common.prototype':'नमुना बुकिंग · खरे पेमेंट होत नाही',
  'pass.keep':'चढताना हा पास तयार ठेवा. हा खरा MSRTC तिकीट किंवा पेमेंट नाही.','pass.back':'बुकिंग','pass.label':'प्रवास पास · नमुना','pass.qr':'नमुना QR ओळख','manage.label':'बुकिंग व्यवस्थापन · नमुना','manage.existing':'आधीचा प्रवास','manage.open':'बुकिंग उघडा.','manage.id':'बुकिंग क्रमांक','manage.openAction':'प्रवास उघडा','manage.title':'प्रवास व्यवस्थापित करा','manage.cancel':'रद्दीकरण','manage.cancelQuestion':'हा प्रवास रद्द करायचा?','manage.cancelled':'प्रवास रद्द केला','manage.track':'तुमची बस शोधा','manage.saved':'या ब्राउझरमध्ये जतन केलेले','manage.recent':'तुमची अलीकडील बुकिंग','manage.twoBus':'दोन बसांचा प्रवास','manage.direct':'थेट प्रवास','manage.browserOnly':'नमुन्यासाठी फक्त या ब्राउझरमध्ये दाखवले आहे.','fare.standard':'सामान्य भाडे','fare.concession':'सवलत','fare.pay':'तुमचे पेमेंट','fare.paid':'तुम्ही भरले','fare.deduction':'रद्दीकरण कपात','fare.receive':'तुम्हाला मिळेल','status.confirmed':'निश्चित','status.notSelected':'निवडलेले नाही',
  'error.confirmDestination':'तुमचे गंतव्य निश्चित करा','error.whichStop':'तुम्हाला कोणते बसस्थानक अपेक्षित आहे?','error.chooseStop':'योग्य बसस्थानक निवडा.','error.planner':'प्रवास नियोजक','error.wrong':'काहीतरी अडचण आली','error.return':'प्रवास नियोजकाकडे परत जा','error.editJourney':'प्रवासाचा तपशील बदला',
  'prototype.requestReceived':'विनंती समजली','prototype.understood':'हा मार्ग येथे उपलब्ध नाही.','prototype.outside':'तुम्ही {origin} → {destination} हा प्रवास शोधला आहे. हा प्रवास या मर्यादित नमुना नेटवर्कमध्ये उपलब्ध नाही.','prototype.requested':'तुम्ही शोधलेला प्रवास','prototype.limitation':'हा मार्ग सध्याच्या नमुना माहितीत समाविष्ट नाही.','prototype.availableJourneys':'या नमुन्यात उपलब्ध','prototype.puneNashik':'पुणे → नाशिक','prototype.chooseNashik':'नाशिकचे बसस्थानक निवडा','prototype.mumbaiPune':'मुंबई → पुणे','prototype.direct':'थेट सेवा','prototype.puneSatara':'पुणे → सातारा','prototype.puneDemo':'पुणे → नमुना गंतव्य','prototype.connection':'सातारामार्गे एक जोडप्रवास','prototype.choose':'उपलब्ध प्रवास निवडा',
  'a11y.primaryNav':'मुख्य नेव्हिगेशन','a11y.language':'भाषा','a11y.goPlanner':'प्रवास नियोजकाकडे जा','a11y.journeyPlanner':'प्रवास नियोजक','a11y.currentSearch':'सध्याचा शोध','a11y.sort':'सेवांची क्रमवारी','a11y.bookingProgress':'बुकिंगची प्रगती','a11y.planning':'प्रवास नियोजन सुरू आहे',
  'search.hero':'तुम्हाला कुठे जायचे आहे ते सांगा. योग्य एसटी सेवा आम्ही शोधू.','search.finding':'बस शोधत आहोत…','search.understood':'प्रवास समजला. बस शोधत आहोत…','search.unavailable':'सोप्या भाषेतील शोध सध्या उपलब्ध नाही. खालील तपशील वापरा.','search.demoJourneys':'नमुना प्रवास','search.tryRoute':'उपलब्ध मार्ग वापरून पहा','search.demoJourneyCount':'या {count} नमुना प्रवासांपैकी एक निवडा','search.aboutDemo':'नमुना माहितीबद्दल','search.supported':'उपलब्ध नमुना प्रवास','search.viewExamples':'उदाहरणे पहा','search.demoHubs':'नमुना केंद्रे','search.demoRoutes':'नमुना मार्ग','search.syntheticFooter':'कृत्रिम वेळापत्रकांचा वापर करणारी नमुना प्रवास सेवा','search.noPaymentFooter':'खरे बुकिंग किंवा पेमेंट होत नाही','search.puneNashikHint':'नाशिकचे बसस्थानक निवडा','search.mumbaiPuneHint':'शिवनेरी आणि ई-शिवाई','search.directService':'थेट सेवा','search.connectionHint':'सातारामार्गे एक जोडप्रवास',
  'network.eyebrow':'उदाहरणासाठी कृत्रिम माहिती','network.title':'उपलब्ध नमुना प्रवास','network.range':'हा नमुना {start} ते {end} या काळात फक्त खालील प्रवासांना समर्थन देतो.','network.tomorrow':'उद्या','network.nextDays':'पुढील 14 दिवस','network.puneNashik':'थेट सेवा. महामार्ग, सीबीएस किंवा नाशिक रोड निवडा.','network.mumbaiPune':'थेट प्रीमियम आणि सामान्य सेवांची उदाहरणे.','network.puneSatara':'थेट सेवेचे उदाहरण.','network.puneDemo':'सातारामार्गे एक जोडप्रवास.','network.disclaimer':'वेळापत्रक, भाडे, ट्रॅकिंग आणि उपलब्धता कृत्रिम आहेत—अधिकृत MSRTC माहिती नाही.',
  'connection.eyebrow':'जोडप्रवास','connection.changeOnce':'{stop} येथे एकदा बस बदला.','connection.total':'एकूण {duration}','connection.transfer':'{stop} येथे बदल · {duration}','connection.summary':'{stop} येथे बस बदलून एक प्रवास.','connection.help':'त्याच बसस्थानकावर थांबा. बुकिंग आणि प्रवास पासमध्ये दोन्ही बस दिसतील.','connection.choose':'हा प्रवास निवडा',
  'booking.progress':'बुकिंगची प्रगती','booking.prototypeOnly':'फक्त नमुन्यासाठी:','booking.fakeDetails':'काल्पनिक नाव वापरा; खरी वैयक्तिक माहिती भरू नका.','booking.eligibility':'सवलत केवळ नमुना आहे. २५ किंवा कमी वयाच्या विद्यार्थ्यांना १०%; ६०+ ज्येष्ठांना २०% सवलत.','booking.recovery':'पेमेंट पुनर्प्राप्ती दाखवा','booking.recoveryHelp':'पेमेंट यशस्वी आणि आरक्षण अयशस्वी अशी नमुना स्थिती दाखवा.','booking.paymentNotice':'हे नमुना पेमेंट आहे; कोणतेही पैसे हस्तांतरित होत नाहीत.','booking.payMock':'₹{amount} नमुना पेमेंट करा','booking.paymentReceived':'पेमेंट मिळाले','booking.confirmReservation':'आरक्षण निश्चित करा.','booking.confirmHelp':'तुमचे नमुना पेमेंट सुरक्षित आहे. एकदाच पुष्टी करा; पुन्हा पेमेंट करू नका.','booking.confirmSeats':'आसने निश्चित करा','booking.journeyBooked':'प्रवास बुक झाला','booking.ready':'तुमचा प्रवास तयार आहे.','booking.reference':'बुकिंग {id}','booking.openPass':'प्रवास पास उघडा','booking.paymentProtected':'पेमेंट सुरक्षित आहे','booking.notConfirmed':'आसन निश्चित करता आले नाही.','booking.refundPending':'नमुना पेमेंट मिळाले आणि परतावा {status} आहे. आसन पुन्हा उपलब्ध आहे.','booking.window':'खिडकी',
  'receipt.glance':'बुकिंगचा सारांश','receipt.passengerNext':'पुढे प्रवाशाची माहिती','receipt.twoTickets':'दोन बसांची तिकिटे','receipt.status':'स्थिती','receipt.total':'एकूण भाडे',
  'manage.yourBooking':'तुमचे बुकिंग','manage.bookingId':'बुकिंग क्रमांक: {id}','manage.deadline':'अंतिम वेळ {time}','manage.refund':'परतावा {status}','manage.refundHelp':'रद्दीकरण पूर्ण झाले. या नमुन्यात परताव्याची प्रगती कृत्रिम आहे.','manage.advanceRefund':'नमुना परतावा पुढे न्या','manage.reviewRefund':'रद्द करण्यापूर्वी वरील परतावा तपासा. रद्द केल्यावर आसन मोकळे होईल.','manage.cancelAction':'प्रवास रद्द करा','manage.cannotCancel':'हा प्रवास आता रद्द करता येणार नाही.','fare.nonRefundable':'परत न मिळणारे शुल्क',
  'tracking.awaiting':'बस नेमण्याची प्रतीक्षा','tracking.departure':'प्रस्थान {time}','tracking.updated':'अद्ययावत {time}','tracking.nextStop':'पुढील थांबा: {stop}','tracking.simulation':'हे मार्गावरील स्थान कृत्रिम नमुना आहे; प्रत्यक्ष MSRTC GPS माहिती नाही.','tracking.demoState':'नमुना स्थिती','tracking.changeState':'दुसरी ट्रॅकिंग स्थिती पाहा','tracking.notice':'नमुना सूचना: प्रत्यक्ष सेवेत बस नेमली किंवा प्रवास सुरू झाला की माहिती येथे दिसेल.','tracking.state.BUS_NOT_ASSIGNED':'अद्याप उपलब्ध नाही','tracking.state.BUS_ASSIGNED':'बस नेमली आहे','tracking.state.TRACKING_AVAILABLE':'ट्रॅकिंग उपलब्ध','tracking.state.TRIP_STARTED':'प्रवास सुरू','tracking.state.LOCATION_STALE':'स्थान जुने आहे','tracking.state.TRIP_COMPLETED':'प्रवास पूर्ण','tracking.message.BUS_NOT_ASSIGNED':'वाहन नेमल्यानंतर बसची माहिती येथे दिसेल.','tracking.message.BUS_ASSIGNED':'तुमची बस नेमली आहे.','tracking.message.TRACKING_AVAILABLE':'प्रस्थानाची वेळ जवळ आल्यावर ट्रॅकिंग उपलब्ध होईल.','tracking.message.TRIP_STARTED':'कृत्रिम नमुना फीडमधील सध्याचे स्थान.','tracking.message.LOCATION_STALE':'स्थान अलीकडे अद्ययावत झालेले नाही.','tracking.message.TRIP_COMPLETED':'हा प्रवास पूर्ण झाला आहे.',
  'complaint.prefilled':'{journey}. प्रवासाची माहिती आधीच भरली आहे.','complaint.booking':'बुकिंग {id}. प्रवासाची माहिती आधीच भरली आहे.','complaint.selected':'निवडले: {name}','complaint.tooLarge':'५ MB पेक्षा लहान प्रतिमा निवडा.','complaint.invalidType':'JPG, PNG किंवा HEIC सारखी प्रतिमा निवडा.','complaint.photoPreview':'निवडलेल्या पुराव्याचे पूर्वदृश्य','complaint.submitted':'नमुना तक्रार नोंदवली','complaint.thanks':'माहिती दिल्याबद्दल धन्यवाद.','complaint.reference':'संदर्भ क्रमांक','complaint.journey':'प्रवास','complaint.category':'प्रकार','complaint.status':'स्थिती','complaint.evidence':'जोडलेला पुरावा','complaint.passenger':'प्रवासी','complaint.date':'प्रवासाची तारीख','complaint.service':'सेवा','complaint.boarding':'चढण्याचे ठिकाण','complaint.destination':'गंतव्य','complaint.seats':'आसने','complaint.bus':'नेमलेली बस',
  'complaint.category.BUS CONDITION':'बसची स्थिती','complaint.category.STAFF':'कर्मचारी','complaint.category.JOURNEY':'प्रवास','complaint.category.SAFETY':'सुरक्षा','complaint.category.CLEANLINESS':'स्वच्छता','complaint.category.FACILITIES':'सुविधा','complaint.category.OTHER':'इतर','complaint.issue.Broken seat':'तुटलेले आसन','complaint.issue.AC not working':'एसी चालत नाही','complaint.issue.Window issue':'खिडकीची समस्या','complaint.issue.Charging point not working':'चार्जिंग पॉइंट चालत नाही','complaint.issue.Cleanliness issue':'स्वच्छतेची समस्या','complaint.issue.Other bus-condition issue':'बसच्या स्थितीची इतर समस्या','complaint.issue.Conductor behaviour':'वाहकाचे वर्तन','complaint.issue.Driver behaviour':'चालकाचे वर्तन','complaint.issue.Ticketing issue':'तिकीट समस्या','complaint.issue.Other staff issue':'कर्मचाऱ्यांशी संबंधित इतर समस्या','complaint.issue.Bus delayed':'बस उशिरा आली','complaint.issue.Bus did not arrive':'बस आली नाही','complaint.issue.Wrong boarding information':'चढण्याच्या ठिकाणाची चुकीची माहिती','complaint.issue.Unscheduled stop':'अनियोजित थांबा','complaint.issue.Other journey issue':'प्रवासाशी संबंधित इतर समस्या','complaint.issue.Unsafe driving':'असुरक्षित वाहनचालकपणा','complaint.issue.Safety concern':'सुरक्षेची चिंता','complaint.issue.Bus cleanliness':'बसची स्वच्छता','complaint.issue.Waiting-area issue':'प्रतीक्षालयाची समस्या','complaint.issue.Other issue':'इतर समस्या',
  'voice.permission':'मायक्रोफोनची परवानगी घेत आहोत…','voice.unsupported':'या ब्राउझरमध्ये आवाजाने शोध उपलब्ध नाही. प्रवास टाइप करता येईल.','voice.denied':'मायक्रोफोनची परवानगी मिळाली नाही. प्रवास टाइप करता येईल.','voice.transcribing':'तुमचा प्रवास लिहून घेत आहोत…','voice.recordingError':'आवाज नोंद पूर्ण झाली नाही. प्रवास टाइप करता येईल.','voice.noSpeech':'प्रवासाची विनंती ऐकू आली नाही. पुन्हा बोला किंवा टाइप करा.','voice.transcriptionError':'आवाजाचे शब्द लिहून घेता आले नाहीत. प्रवास टाइप करता येईल.','voice.stopped':'आवाजाने शोध थांबवला. टाइप केलेला प्रवास बदललेला नाही.',
  'api.SERVICE_UNAVAILABLE':'सेवा तात्पुरती उपलब्ध नाही. तुमचा तपशील येथेच आहे—पुन्हा प्रयत्न करा.','api.PHOTO_TOO_LARGE':'५ MB पेक्षा लहान प्रतिमा निवडा.','api.PHOTO_INVALID_TYPE':'JPG, PNG किंवा HEIC सारखी प्रतिमा निवडा.','api.BOOKING_NOT_FOUND':'हे बुकिंग सापडले नाही. बुकिंग क्रमांक तपासून पुन्हा प्रयत्न करा.','api.DATE_OUT_OF_RANGE':'या नमुन्यासाठी {start} ते {end} मधील तारीख निवडा.','api.DATE_OUTSIDE_DEMO_WINDOW':'या नमुन्यासाठी {start} ते {end} मधील तारीख निवडा.','api.INVALID_CONNECTION':'या सेवा आता योग्य जोडप्रवास तयार करत नाहीत. पुन्हा शोधा.','api.TRIP_UNAVAILABLE':'यापैकी एका बसमध्ये आसन उपलब्ध नाही. पुन्हा शोधा.','api.INVALID_SEAT_SELECTION':'प्रत्येक बसमध्ये एक आसन निवडा.','api.default':'ही कृती पूर्ण करता आली नाही. पुन्हा प्रयत्न करा.',
  'status.DRAFT':'मसुदा','status.SEATS_HELD':'आसने राखीव','status.PAYMENT_PENDING':'पेमेंट प्रलंबित','status.PAYMENT_RECEIVED':'पेमेंट मिळाले','status.CONFIRMING':'पुष्टी सुरू','status.CONFIRMED':'निश्चित','status.CANCELLED':'रद्द','status.FAILED':'अयशस्वी','status.PENDING':'प्रलंबित','status.PROCESSING':'प्रक्रिया सुरू','status.COMPLETED':'पूर्ण','status.SUBMITTED':'नोंदवली','status.UNDER_REVIEW':'तपासणी सुरू','status.RESOLVED':'निकाली',
}
export const dictionaries = { en, mr }
export type TranslationKey = string
export function translate(locale: Locale, key: TranslationKey, values: Record<string, string | number> = {}) { return (dictionaries[locale][key] ?? dictionaries.en[key] ?? key).replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`)) }

const marathiStops: Record<string, string> = {
  Pune: 'पुणे', 'Pune Station': 'पुणे स्थानक', Mumbai: 'मुंबई', 'Mumbai Central': 'मुंबई सेंट्रल',
  Nashik: 'नाशिक', 'Nashik CBS': 'नाशिक सीबीएस', 'Nashik Mahamarg': 'नाशिक महामार्ग', 'Nashik Road': 'नाशिक रोड',
  Satara: 'सातारा', 'Satara Bus Stand': 'सातारा बसस्थानक', 'Demo Destination': 'नमुना गंतव्य',
  'Near Talegaon toll plaza': 'तळेगाव टोलनाक्याजवळ',
}

const marathiDescriptions: Record<string, string> = {
  'Central Bus Stand in Nashik city.': 'नाशिक शहरातील मध्यवर्ती बसस्थानक.',
  'Mahamarg bus stop on the Mumbai–Agra highway.': 'मुंबई–आग्रा महामार्गावरील बस थांबा.',
  'Mahamarg bus stop on the Mumbai-Agra highway.': 'मुंबई–आग्रा महामार्गावरील बस थांबा.',
  'Boarding point near Nashik Road railway station.': 'नाशिक रोड रेल्वे स्थानकाजवळील चढण्याचे ठिकाण.',
}

const marathiServices: Record<string, string> = {
  'Demo Destination Satara Ordinary': 'नमुना गंतव्य–सातारा साधी बस',
  'Demo Destination Satara Semi Luxury': 'नमुना गंतव्य–सातारा निमआराम',
  'Pune Nashik E Shivai': 'पुणे–नाशिक ई-शिवाई',
  'Pune Nashik Ordinary': 'पुणे–नाशिक साधी बस',
  'Pune Nashik Semi Luxury': 'पुणे–नाशिक निमआराम',
  'Pune Nashik Shivneri': 'पुणे–नाशिक शिवनेरी',
  'Mumbai Pune E Shivai': 'मुंबई–पुणे ई-शिवाई',
  'Mumbai Pune Shivneri': 'मुंबई–पुणे शिवनेरी',
  'Nashik Pune E Shivai': 'नाशिक–पुणे ई-शिवाई',
  'Nashik Pune Ordinary': 'नाशिक–पुणे साधी बस',
  'Nashik Pune Semi Luxury': 'नाशिक–पुणे निमआराम',
  'Nashik Pune Shivneri': 'नाशिक–पुणे शिवनेरी',
  'Pune Mumbai E Shivai': 'पुणे–मुंबई ई-शिवाई',
  'Pune Mumbai Shivneri': 'पुणे–मुंबई शिवनेरी',
  'Pune Satara Ordinary': 'पुणे–सातारा साधी बस',
  'Pune Satara Semi Luxury': 'पुणे–सातारा निमआराम',
  'Satara Demo Destination Ordinary': 'सातारा–नमुना गंतव्य साधी बस',
  'Satara Demo Destination Semi Luxury': 'सातारा–नमुना गंतव्य निमआराम',
  'Satara Pune Ordinary': 'सातारा–पुणे साधी बस',
  'Satara Pune Semi Luxury': 'सातारा–पुणे निमआराम',
  'Ordinary': 'साधी बस',
  'Semi Luxury': 'निमआराम',
  'Shivneri': 'शिवनेरी',
  'E Shivai': 'ई-शिवाई',
}

export function localizeStop(locale: Locale, value: string | null | undefined) {
  if (!value) return ''
  return locale === 'mr' ? marathiStops[value] ?? value : value
}

export function localizeStopDescription(locale: Locale, value: string) {
  return locale === 'mr' ? marathiDescriptions[value] ?? value : value
}

export function localizeService(locale: Locale, value: string | null | undefined) {
  if (!value) return ''
  return locale === 'mr' ? marathiServices[value] ?? value : value
}

const canonicalStops: Record<string, string> = {
  ...Object.fromEntries(Object.entries(marathiStops).map(([english, marathi]) => [marathi, english])),
  'पुने': 'Pune', 'पूणे': 'Pune',
  'नाशीक': 'Nashik', 'नासिक': 'Nashik',
  'मुम्बई': 'Mumbai', 'सतारा': 'Satara',
}
export function canonicalStop(value: string) { return canonicalStops[value] ?? value }
